services:
  - type: web
    name: mcp-chat-backend
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add other env vars as needed
